# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: bms-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bms_app
    depends_on:
      - mongo
    networks:
      - bms-network

  mongo:
    image: mongo:latest
    container_name: bms-mongo
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db
    networks:
      - bms-network

volumes:
  mongo_data:

networks:
  bms-network:
    driver: bridge
