# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: todo-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todo_app
    depends_on:
      - mongo
    networks:
      - todo-network

  mongo:
    image: mongo:latest
    container_name: todo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-network

volumes:
  mongo_data:

networks:
  todo-network:
    driver: bridge
